//
//  User.swift
//  Flokk
//
//  Created by Gannon Prudhomme on 2/3/17.
//  Copyright © 2017 Flokk. All rights reserved.
//

import Foundation
import UIKit

// A class that represents all user in Flokk.
// There will be a user clas created for the main user(the one that is logged in and using the local app),
//  as well as each user the main user interacts with.
class User: Hashable { // Hashable so it can be used as a key in a dictionary(for comments)
    var uid: String! // The unique ID for this user, generated by Firebase
    var handle: String // A completely unique identifier(ie. @gannonprudhomme)
    var fullName: String
    var profilePhoto: UIImage
    var email: String! // The email of this user, usually not going to be generated
    
    var groups = [Group]() // The groups this user is in
    var groupIDs = [String]() // The IDs of all the groups this user is in
    
    var friends = [User]() // Array of all friends this user has that have already been loaded
    var friendIDs = [String]() // Array of the ids of friends this user has, don't need all of the user's data the entire time
    
    var incomingFriendRequests = [String]() // Array of user ids that requested to be this user's friend
    var outgoingFriendRequests = [String]() // Array of user ids this user requested to be friends with
    
    var groupInvites: [String]! // Array of ID's for the group the user has been invited to
    
    var notifications = [Notification]() // The user's notifications
    
    var uploadedPostsData = [String : [String : Double]]() // Dictionary of posts that were saved, with the key being the groupID
    var savedPostsData = [String : [String : Double]]() // Dictionary of posts that were uploaded, with the key being the groupID
    
    init(uid: String, handle: String, fullName: String) {
        self.uid = uid
        self.handle = handle
        self.fullName = fullName
        self.profilePhoto = UIImage(named: "AddProfilePic")! //temporary
    }
    
    init(uid: String, handle: String, profilePhoto: UIImage) {
        self.uid = uid
        self.handle = handle
        self.profilePhoto = profilePhoto
        self.fullName = ""
    }
    
    init(uid: String, handle: String, fullName: String, groupIDs: [String]) {
        self.uid = uid
        self.handle = handle
        self.fullName = fullName
        self.profilePhoto = UIImage(named: "AddProfilePic")!
        
        self.groupIDs = groupIDs
    }
    
    init(uid: String, handle: String, fullName: String, profilePhoto: UIImage) {
        self.uid = uid
        self.handle = handle
        self.fullName = fullName
        self.profilePhoto = profilePhoto
    }
    
    init(uid:String, handle: String, fullName: String, profilePhoto: UIImage, groupIDs: [String]) {
        self.uid = uid
        self.handle = handle
        self.fullName = fullName
        self.profilePhoto = profilePhoto
        
        self.groupIDs = groupIDs
    }
    
    func getInitials() -> String {
        // Split the name by the spaces
        let array = self.fullName.components(separatedBy: " ")
        
        if array.count > 1 {
            // Get the first and last words from the array
            let firstName = array[0]
            let lastName = array[array.count - 1]
            
            
            return "\(firstName[firstName.startIndex])\(lastName[lastName.startIndex])"
        } else {
            let string = array[0]
            
            return "\(string[string.startIndex])"
        }
    }
    
    // Method needed to implement hashable
    // Used to store and match values in a dictionary
    var hashValue: Int {
        get {
            // As the handles are unique, this value is also unique
            return handle.hashValue
        }
    }
    
    // The func Equatable, needed to implement Hashable
    static func ==(lh: User, rh: User) -> Bool {
        return lh.handle == rh.handle //all handles are unique
    }
    
    // Override the description variable to display information
    // About this class when this class is printed - like Java's .toString() method
    public var description: String {
        return "User: handle: \(handle) full name: \(fullName)"
    }
}

// Determine the various statuses of a friend request
// To determine how to display the add friend button
enum FriendRequestStatus {
    case THIS_USER_SENT
    case THIS_USER_RECEIVED
    case THIS_USER_DENIED
}
